name: conduit_open_api_fork
version: 1.0.0-b9
homepage: https://github.com/qscr/open-api-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  conduit_codable_fork: ^1.0.0-b5
  meta: ^1.1.5
dev_dependencies:
  dcli: ^1.0.0
  lint: ^1.5.3
  test: ^1.3.0
